# Generated by Django 2.1.4 on 2018-12-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181210_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('list', 'order')},
        ),
    ]
